logger:
  level: debug
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
  filename: 'logs.log'
  filemode: 'w'
  encoding: 'utf-8'
  style: '%'
  handlers: ['console', 'file']
  console:
    class: logging.StreamHandler
    level: debug
    formatter: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file:
    class: logging.FileHandler
    level: debug
    formatter: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
```

```python